### ISSUE TITLE
[ BN ] Regarding Ruby references in the lesson translations.

### ISSUE THREAD

**Issue by code-shoily** [doomspork/elixir-school#1002]
I'm in the process of reviewing some of the translations of lessons and in a few places there are references to `Ruby` i.e. on the `Mix` and `Basics` chapter. While it's helpful to have a reference handy, but people who'd be coming with the interest of a Bengali translation wouldn't mostly be `Ruby` programmers since we don't have many of them here. I was thinking if I'd remove these references and add a more general tone to it? For example, when thinking `Mix` I instantly thought of `Leiningen` and same mental "Clojurian" comparison came in my head with the `Pipe Operator`, `Symbol` etc. But I guess we should keep it agnostic of other (at least non-Erlang) language references **or** add more than just one "comparable" languages when the feature in question is less unique to that language?

Just a thought, what do you say? 

cc: @masnun @prio101 @doomspork @nscyclone ?

**Comment by masnun** [comment]
Agreed.

**Comment by armanhusain** [comment]
Agreed, we need to have a more neutral documentation for programmers with a non-Ruby background. Bengali aside, there should not be references to another language, rather, independent explanations for topics that are unique to this language.

**Comment by code-shoily** [comment]
@armanhusain you cannot let go of Erlang when it comes to advanced topics such as OTP and concurrency because Elixir is based on top of those, reference of it is bound to arrive and it's natural for it to be so. References to another language cannot be entirely removed, that'd be silly in places. 

Elixir is a new language and most of the people coming on board will have some programming experiences, I think. So that will be easier to cross-reference examples similar in other languages. So that is not bad if you ask me. I was just mentioning `Ruby` because it comes a bit more often as a referring "third party language" not in this site, but in quite a few other places. In Bangladesh, we have very few Ruby devs and from what I see, most Elixir enthusiasts here have JavaScript background. So, instead of pigeon-holing `Ruby`, one or two more language reference would be nice, just so that people can relate. I am speaking for the Bengali section because I am one of the contributors here and I intend to add a reference or two (or remove some and expand the definition) and wanted other contributors' opinion on it, that's all. I am not entirely against cross-language references especially in languages where most entrants have some programming experience under their belt.

**Comment by prio101** [comment]
totally agreed with @code-shoily ...

**Comment by doomspork** [comment]
Hmm.  This is tough and I'd like to think it over a bit.  The purpose of referencing other languages is to assist folks with comparing it to things they know.  While the some people may not have Ruby backgrounds the vast majority of folks coming to Elixir do.

@nscyclone / @pjhampton / @pragmaticivan / et al — any thoughts?

**Comment by pragmaticivan** [comment]
I agree with @code-shoily about the OTP part. But I still think removing Ruby as a reference to use general context would be less helpful. I would rather add javascript reference too, since most of the web developers are familiar with javascript.

I think the vast majority are coming from Ruby. But also we should take into consideration to take a look at resources of where José Valim took inspiration to write something. I bet Symbols is a good case to explain that.

**Comment by pjhampton** [comment]
Hmm, there is a [Scala project](http://docs.scala-lang.org/tutorials/) where the maintainers tried to tie the lessons to other langs (Java, Python, Ruby). They didn't get very far with it except for Java because it was a natural progression from Java to Scala. I think Ruby is the closest syntactically and the elixir toolchain is heavily inspired by it. I think if there were semantic comparisons in the lessons then we should consider removing these.

**Comment by doomspork** [comment]
Pinging some of the other translators to get their feedback since this change will impact everyone: @Koziolek / @brain-geek / @gemantzu / @devleoper / @cizixs

**Comment by code-shoily** [comment]
@doomspork I only meant for the Bengali translations :) because it's a rather small community, I know most of them personally, even the ones who're planning to join up. Only one or two from the Ruby background and they're fairly advanced developers who probably went way ahead from documentation. I was asked quite a few number that if knowing Ruby would help to start off with Elixir, or if they'd be at any disadvantage for not knowing Ruby etc. I figured, the Bengali translation would mostly cater to beginner to intermediate programmers who might naturally ask these questions or think like that. That's why I had raised this issue to i) Add more languages in examples and ii) Expand on the definition of things a bit more in `Bengali` translations. I don't think the same should hold for other countries or languages because a fair amount of programmers are coming from the Ruby background so like @pragmaticivan had said, it would be less helpful. But in case of Bengali, a large number I see gaining interest in Elixir are from JavaScript/Java background (and a few Pythonistas here and there). So my question was more local to the `Bengali` translations.

**Comment by gemantzu** [comment]
In my opinion it will be more helpful if we add more instead of moving to a more general approach with no language reference. I think the Ruby parts are not that many and it will not create a big impact to add references to a couple more languages. @code-shoily have in mind though, that most people coming to elixir are have a Ruby background, at least up until now.

**Comment by nscyclone** [comment]
I totally agree with @pragmaticivan and @gemantzu.
Removing existing references doesn't offer that much benefits but adding more is a good option to provide a faster and more comfy way to learn for those who has some background exprience with any other languages.

**Comment by code-shoily** [comment]
Thanks for the inputs everyone :) I think I'll just add references to other languages in my translations when appropriate.
