### ISSUE TITLE
Outdated/incorrect state[:key] syntax

### ISSUE THREAD

**Issue by schmurfy** [doomspork/elixir-school#1118]
I am not sure which is it but what this page shows: https://elixirschool.com/lessons/basics/testing/
does not work with elixir 1.4.4, while digging on exiting elixir projects I found the following to be working but I am not sure whether it is the correct way to do it or not:

```elixir
defmodule ModTest do
  use ExUnit.Case
  doctest Mod
  
  setup_all do
    {:ok, address: "192.168.0.108"}
  end
  
  test "something", ctx do
    assert ctx.address == 42
  end
end
```
What is the corret way to use state in tests ?

**Comment by gemantzu** [comment]
What do you mean it does not work with Elixir 1.4.4? Can you show us an error that you get when running this test? I just tested it and it works just perfect. What is that 42 number you are using in your test?

**Comment by schmurfy** [comment]
I did more testing and I am not clear on what is exactly my issue but you are right it works with a simple case, I oversimplified the test case but for some reasons my real usecase does not work.

I am still discovering elixir and I have no real idea what the differences are between ".ex" and ".exs" files, is there anything particular about exs files ?

I currently playing with the nksip erlang library and here is the test that fails:

```elixir
defmodule SipTest do
  use ExUnit.Case

  setup do
    {:ok, address: "192.168.0.108"}
  end
  
  test "rr" do
    {:ok, _} = :nksip.start("client", sip_local_host: state[:address])
  end
```

What I get is:
```
warning: variable "state" does not exist and is being expanded to "state()", please use parentheses to remove the ambiguity or change the variable name
  test/sip_test.exs:9

** (CompileError) test/sip_test.exs:9: undefined function state/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

But writing the same code passing `ctx` and using `ctx.address` works... Can you tell me why ?

**Comment by gemantzu** [comment]
By convention, .ex files are compiled to .BEAM files that are executed by the beam virtual machine, and .exs files are compiled in memory, so they are mostly scripts or test files that just have to run once. 

In your test named "rr", you use a state variable but you do not read it from setup. In order to do so, your function definition should be 
```elixir
test "rr", state do
```
State in elixir is explicit, not implicit. Therefore, what you return from your setup, has to be "captured" somehow by your tests if you want to use it. If you do that, I believe your test should pass (I don't know anything about that library though, so it's up to you).

**Comment by schmurfy** [comment]
It does work indeed, my bad xD
Thanks for the precisions concerning exs files.
