### ISSUE TITLE
404 not found from google links

### ISSUE THREAD

**Issue by axelson** [doomspork/elixir-school#1134]
This has happened a few times now and it's been getting annoying. Google is returning links like:

https://elixirschool.com/lessons/specifics/plug/

Which renders a text string saying "Not found" and that's it.

It appears that the correct link is (depending on your locale):

https://elixirschool.com/en/lessons/specifics/plug/

I think that the previous link should return do some auto-detection, ask you to choose the locale, or default to a locale.

**Comment by doomspork** [comment]
Thank you for the report @axelson!  

@eksperimental it seems like the redirect plugin is not doing it's job 😰

**Comment by doomspork** [comment]
I've bumped the Jekyll version to no avail.  Still digging in.  @nscyclone could you take a peek if you get a chance?

**Comment by nscyclone** [comment]
@doomspork We have a [manual redirect](https://github.com/doomspork/elixir-school/commit/e689f70760e7a3ff6203cfa4cf291f968edba46f) set up from the index page to the `en` index. As was stated in the commentary from commit linked above it was made due to a [Jekyll issue](https://github.com/jekyll/jekyll/pull/6058) that seems to be fixed in the [latest major release](https://github.com/jekyll/jekyll/releases/tag/v3.5.0).
We also use the [`pretty` permalink](https://jekyllrb.com/docs/permalinks/) which means that the post links don't have the extension and are being redirected to `index.html` in the post's folder. I guess the 404 issue is caused because the generated redirect file is located not at https://elixirschool.com/lessons/specifics/plug/index.html as expected but at https://elixirschool.com/lessons/specifics/plug.html. So I guess we could just update all the gems and add a trailing slash to each `redirect_from` clause in English pages' front matters.

I am not 100% sure about this but don't yet have anything else to suggest. Please take a look at #1135.

**Comment by doomspork** [comment]
Thanks again for bringing this to our attention @axelson 👍 

Huge thanks to @nscyclone for finding the solution so quickly
