### ISSUE TITLE
Glossary proposal

### ISSUE THREAD

**Issue by brain-geek** [doomspork/elixir-school#162]
The problem: right now there are some wording issues related to Elixir-specific (or other non-widely used) terms when translating. Also, there is a problem whether some things should be translated at all. And I'm not the only one having this problem:

> There are many English terms that could not be 1:1 translated to Vietnamese. Most of the cases, translated terms make no senses whatsoever. 

And there's even small discussion [in this topic](https://github.com/doomspork/elixir-school/pull/103).

> Note: I couldn't find a good translation for callback, so I leave as it is but in italic.
> Note 2: The word handler is not easy to translate, so I used the word "processador" which is something similar.

[Source](https://github.com/doomspork/elixir-school/pull/153)

Also, for all terms, we should have stable translations in one language to improve reading experience.

A possible solution for this problem is having some kind of glossary per language. [Example I made for Russian language](https://github.com/brain-geek/elixir-school/blob/ru_glossary/ru/GLOSSARY.md)

This will improve translation quality and simplify terminology translation lookups.

Let's discuss this.

**Comment by pjhampton** [comment]
It sounds like a good idea to me, but then again... I'm not a translator. Thoughts @pragmaticivan?

**Comment by erickgnavar** [comment]
Good idea, I have the same problem when I translate terms like "pattern matching" or "function clause" to spanish.

**Comment by pragmaticivan** [comment]
I like the idea, in Portuguese some of the terms are really hard to translate. Some of them I just don't translate because they're common terms in programming.

**Comment by doomspork** [comment]
I'm :+1: for a glossary.  I think it would be useful even for English speakers.

**Comment by brain-geek** [comment]
I've added the first version of glossary in #174 . Feedback is welcome.

**Comment by setzer777** [comment]
Do we have an spanish glossary at this moment?

**Comment by doomspork** [comment]
No we do not @setzer777.  Feel free to check out #174 and leave your feedback/suggestions :grinning:

**Comment by setzer777** [comment]
I think this idea is super great! 
Sometimes we don't have to translate every term into our language, because of two things.

1.  The translation effort grows so bad, because we need to find adequate words to make our translation work.
2.  Specially with the technical terms like Pattern Matching, at least in Spanish, when we try to translate that, it turns to be a really poor translation, and it's not because of the translator, it's because there isn't really a synonym or a single way to make the translation fully match the real term. And this is something I've been claiming a lot in technology translated books, the translated terms are not an easy way to google the real topic, and that makes the process slower and unclear.

The glossary would help all the readers to really google-dig into the real terms, and us to avoid using miss-understandable words delivering weird translations.

Kinda long opinion, isn't it? haha

**Comment by doomspork** [comment]
I've merged the first glossary in #174. 

Thank you for sharing your thoughts @setzer777 :+1:

**Comment by doomspork** [comment]
Closing because we now have a Glossary.  Thanks again @brain-geek and @pragmaticivan :+1:
