### ISSUE TITLE
Automatic 'table of contents' building

### ISSUE THREAD

**Issue by brain-geek** [doomspork/elixir-school#336]
Hey!

I think it would be very useful to have 'table of contents' build automatically in a lesson. The way we do it right now is error-prone.

All data is already there (we always link to all h* elements in a lesson), we just need to use it somehow. 

For example, there is a [js script](https://github.com/ghiculescu/jekyll-table-of-contents) to do that.

What do you think?

**Comment by doomspork** [comment]
@brain-geek if you want to set this up, I'm open to using it 👍

**Comment by Koziolek** [comment]
Remember guys that we need to introduce this in all files in all translations (lot of testing).

**Comment by doomspork** [comment]
Agreed @Koziolek

**Comment by nscyclone** [comment]
I am already working on this. (Just in case if someone wanted to start.)

**Comment by doomspork** [comment]
Thank you @nscyclone 💜

**Comment by nscyclone** [comment]
It would be nice to have some sort of rules to share with the authors of pending translations because they do not know about this feature yet and still continue creating manual TOCs.
I think we could update `README` or `CONTRIBUTING` to reflect the usage of the TOC generator template and then close this issue. Recommendations for translations are somehow located in `README` so I can't decide where should we place our new advice. There may also be something else worthy to be pointed for contributors.
#194 is still a work in progress.
Do you have any suggestions, @doomspork?

**Comment by doomspork** [comment]
Very good point @nscyclone.  I'm not sure people read either of those documents but that is certainly a start.  We should probably also ask the existing PR authors to update their changes, right?

**Comment by nscyclone** [comment]
@doomspork, here is [an interesting thing](https://github.com/blog/2111-issue-and-pull-request-templates) we could look at. This may help us with newer PRs until we release new `CONTRIBUTING` and `README` (actually it may help after that too). Anyway, I couldn't find any other solution so I think we could do nothing else but leave a comment in every existing PR manually.

**Comment by nscyclone** [comment]
@doomspork, I've just left a copy of advice in every open PR with translations: #229, #244, #264, #316, #319, #320, #326, #343, #345, #347, #350, #352, #353 and #359.

**Comment by doomspork** [comment]
Thank you @nscyclone, that is tremendously helpful!

**Comment by doomspork** [comment]
Huge thanks to @nscyclone and @brain-geek for this 👍
