### ISSUE TITLE
Improve explanation in Pattern Matching lesson

### ISSUE THREAD

**Issue by holsky** [doomspork/elixir-school#797]
What really helped me understand how pattern matching in Elixir/Erlang work is to compare the '=' operator to the equals sign in algebra. I would phrase the introductory sentence in the section like so. What do you think?

Are you ready for a curveball? In Elixir, the = operator is actually a match operator, comparable to the equals sign in algebra. If you think about it, writing x = x + 1 is fundamentally wrong in algebra, so Elixir does not let you do it. Instead, writing = makes Elixir match the value of variables on the left-hand side with values on the right-hand side. Let's take a look:

(and so on, maybe smaller changes to the examples but I would put that in the Pull Request)

**Comment by ybur-yug** [comment]
`Are you ready for a curveball` might not translate very well. I don't know if I like the algebraic comparison. Thoughts @doomspork? I totally agree that we need some overall refinement especially from the perspective of new people diving in, but worry about getting too dense too early myself.

**Comment by nscyclone** [comment]
@ybur-yug, `Are you ready for a curveball` is already a part of [the original lesson](https://github.com/doomspork/elixir-school/blob/6232c1e585443e4716f613f905b48e52853be226/lessons/basics/pattern-matching.md#L15) and is translated as well. So I don't think there will be any issues related to translations. 

Thanks, @holsky, this is definitely a good idea!
In my opinion, the algebraic comparison is actually one of the simplest way to explain how does this work. I'd suggest something like the following:
`Are you ready for a curveball? In Elixir, the = operator is actually a match operator, comparable to the equals sign in algebra. Writing it turns the whole expression into an equation and makes Elixir match the values on the left hand with the values on the right hand. If the match succeeds, it returns the value of the equation. Otherwise, it throws an error. Let's take a look:`
What do you think?
I'm ready to propose a PR with these changes and I'd also prepare the Russian translation if you find this a good idea.

**Comment by doomspork** [comment]
@nscyclone that sounds great, please open a PR

**Comment by holsky** [comment]
Didn't have time to look before, but looks good :)
