### ISSUE TITLE
iex warning in Basics/Functions example

### ISSUE THREAD

**Issue by dodosiz** [doomspork/elixir-school#985]
Recently, as I was running the Guard example in Basics/Functions 

`
defmodule Greeter do
  def hello(names) when is_list(names) do
    names
    |> Enum.join(", ")
    |> hello
  end

  def hello(name) when is_binary(name) do
    phrase <> name
  end

  defp phrase, do: "Hello, "
end
`

The iex showed me a warning that "variable "phrase" does not exist and is being expanded to "phrase()", please use parentheses to remove the ambiguity or change the variable name"

So I think it would better to put parentheses on [phrase()](https://github.com/doomspork/elixir-school/compare/master...dodosiz:master#diff-0ce807a769b44d72636d4179b0edbd53), what do you think?

**Comment by nscyclone** [comment]
Thanks, @dodosiz!
This is definitely a good catch, some code may produce such warnings because it wasn't yet updated to Elixir 1.4 when this warning [has been introduced](https://github.com/elixir-lang/elixir/issues/3268).
Would you want to send a PR? If so, I suppose it would be nice if you could take care of the [translations](https://github.com/doomspork/elixir-school/search?utf8=%E2%9C%93&q=phrase+%3C%3E+name) too.

**Comment by hanmd82** [comment]
Hi @dodosiz would you like to raise a new PR to close this issue? Otherwise may I take this up? cc @nscyclone

**Comment by dodosiz** [comment]
Yes Han, could you take it up?
________________________________
Από: Mingding Han <notifications@github.com>
Στάλθηκε: Τρίτη, 25 Απριλίου 2017 9:33:50 πμ
Προς: doomspork/elixir-school
Κοιν.: Theodosis Asvestopoulos; Mention
Θέμα: Re: [doomspork/elixir-school] iex warning in Basics/Functions example (#985)


Hi @dodosiz<https://github.com/dodosiz> would you like to raise a new PR to close this issue? Otherwise may I take this up? cc @nscyclone<https://github.com/nscyclone>

**Comment by nscyclone** [comment]
Thanks, @dodosiz!
@hanmd82 has already fixed that in #1064 so I guess there is nothing else left to be worried about.
